#!/usr/bin/env python

import sys
import subprocess

def isValid(username):
    if not username[0].islower():
        return False
    for c in username:
        if not (c.islower() or c.isdigit()):
            return False
        return True

if len(sys.argv) < 2:
    print("Utilisation de la commande : ./deleteuser username")
    exit(0)

username = sys.argv[1]

if not isValid(username):
    print("Erreur : Minuscules et chiffres seulement")
    exit(0)

# Delete shell user
subprocess.call("sudo userdel " + username,shell=True)

# Remove it's home
subprocess.call("sudo rm -rf /home/" + username ,shell=True)
